"""Small, read-only MAPIT client foundation."""

from .auth import (
    CognitoAuthenticator,
    CognitoHTTPError,
    MapitSession,
    SessionRefreshError,
    TemporaryCredentials,
    UnsupportedCognitoChallenge,
)
from .agent import AgentAdapterError, AgentAnswer, AgentRunOutcome, run_agent_once
from .codex_cli_backend import (
    CodexCliBackend,
    CodexCliError,
    CodexCliResult,
    CodexProcessResult,
    CodexRunner,
    build_codex_child_env,
)
from .client import MapitClient, MapitHTTPError, MapitResponseError, MapitResponseTooLarge, MapitTransportError
from .config import MapitConfig, RuntimeConfig, discover_runtime_config
from .realtime import (
    RealtimeClient,
    RealtimeError,
    RealtimeFactoryError,
    RealtimeAuthenticationError,
    RealtimeService,
    RealtimeState,
    account_socket_url,
    create_realtime_service,
    normalize_realtime_message,
    realtime_service_from_saved_session,
)
from .session import ManagedSession, RefreshTokenStore, SessionManager, SessionManagerError, WindowsKeyringRefreshTokenStore
from .telegram_adapter import (
    PrivateTelegramPolicy,
    TelegramAccessPolicy,
    TelegramAdapter,
    TelegramBackend,
    TelegramDispatchResult,
    TelegramSender,
    TelegramUpdate,
    format_agent_answer,
)
from .telegram_credentials import (
    TelegramCredentialStoreError,
    TelegramCredentials,
    WindowsKeyringTelegramCredentialStore,
)
from .telegram_bot import (
    BotApiTransport,
    TelegramBotError,
    TelegramIncomingUpdate,
    TelegramBotPoller,
    TelegramBotSender,
    TelegramPollResult,
)
from .route_input_analyzer import (
    GAP_SOURCES,
    LINESTRING_GAP_DISTRIBUTIONS,
    NAME_ORDER_PATTERNS,
    RouteInputAnalysisError,
    THIRD_ORDINATE_CLASSES,
    analyze_route_input,
    analyze_route_input_sufficiency,
    safe_analyze_route_input,
    safe_analyze_route_input_sufficiency,
)
from .osrm import classify_match_json, classify_match_response

__all__ = [
    "CognitoAuthenticator",
    "AgentAdapterError",
    "AgentAnswer",
    "AgentRunOutcome",
    "CodexCliBackend",
    "CodexCliError",
    "CodexCliResult",
    "CodexProcessResult",
    "CodexRunner",
    "build_codex_child_env",
    "CognitoHTTPError",
    "MapitClient",
    "MapitConfig",
    "MapitHTTPError",
    "MapitTransportError",
    "MapitResponseError",
    "MapitResponseTooLarge",
    "MapitSession",
    "SessionRefreshError",
    "RuntimeConfig",
    "TemporaryCredentials",
    "UnsupportedCognitoChallenge",
    "ManagedSession",
    "RefreshTokenStore",
    "SessionManager",
    "SessionManagerError",
    "WindowsKeyringRefreshTokenStore",
    "discover_runtime_config",
    "run_agent_once",
    "RealtimeClient",
    "RealtimeError",
    "RealtimeFactoryError",
    "RealtimeAuthenticationError",
    "RealtimeService",
    "RealtimeState",
    "account_socket_url",
    "create_realtime_service",
    "normalize_realtime_message",
    "realtime_service_from_saved_session",
    "PrivateTelegramPolicy",
    "TelegramAccessPolicy",
    "TelegramAdapter",
    "TelegramBackend",
    "TelegramDispatchResult",
    "TelegramSender",
    "TelegramUpdate",
    "format_agent_answer",
    "TelegramCredentialStoreError",
    "TelegramCredentials",
    "WindowsKeyringTelegramCredentialStore",
    "BotApiTransport",
    "TelegramBotError",
    "TelegramIncomingUpdate",
    "TelegramBotPoller",
    "TelegramBotSender",
    "TelegramPollResult",
    "RouteInputAnalysisError",
    "GAP_SOURCES",
    "LINESTRING_GAP_DISTRIBUTIONS",
    "NAME_ORDER_PATTERNS",
    "analyze_route_input",
    "analyze_route_input_sufficiency",
    "safe_analyze_route_input",
    "safe_analyze_route_input_sufficiency",
    "THIRD_ORDINATE_CLASSES",
    "classify_match_json",
    "classify_match_response",
]
