"""Build a pure, isolated DEV OAuth-client candidate for the retained owner pool.

This factory adds only a resource server, one public OAuth client, and its
managed-login branding. It never calls AWS or alters the identity pool, owner,
MFA setting, existing OAuth client, application stack, or endpoint state.
"""
from __future__ import annotations

import copy
import re
from typing import Any

from scripts.build_aws_dev_oauth_template import _validate_callback
from scripts.build_aws_shared_identity_dev import (
    SharedIdentityTemplateError,
    build_shared_identity_oauth_setup_retained_template,
)

REGION = "eu-west-1"
STACK_NAME = "honda-mapit-mcp-dev-owner-oauth"
RESOURCE_SERVER_NAME = "honda-mapit-mcp-dev-owner"
CLIENT_NAME = "honda-mapit-mcp-dev-owner-codex"
_ACCOUNT = re.compile(r"[0-9]{12}\Z")
_API_ID = re.compile(r"[a-z0-9]{10}\Z")
_POOL_ID = re.compile(r"eu-west-1_[A-Za-z0-9]{9,45}\Z")
_RESOURCE_NAMES = {"McpResourceServer", "McpUserPoolClient", "McpManagedLoginBranding"}
_RESOURCE_TYPES = {
    "McpResourceServer": "AWS::Cognito::UserPoolResourceServer",
    "McpUserPoolClient": "AWS::Cognito::UserPoolClient",
    "McpManagedLoginBranding": "AWS::Cognito::ManagedLoginBranding",
}


class DevOwnerOAuthTemplateError(ValueError):
    """Safe fixed-category error for invalid owner OAuth template inputs."""


def _fail() -> None:
    raise DevOwnerOAuthTemplateError("dev_owner_oauth_invalid")


def _inputs(account_id: str, api_id: str, owner_pool_id: str, callback_url: str) -> tuple[str, str, str, str]:
    if (type(account_id) is not str or _ACCOUNT.fullmatch(account_id) is None
            or account_id == "000000000000"
            or type(api_id) is not str or _API_ID.fullmatch(api_id) is None
            or type(owner_pool_id) is not str or _POOL_ID.fullmatch(owner_pool_id) is None):
        _fail()
    try:
        callback = _validate_callback(callback_url)
    except Exception:
        _fail()
    return account_id, api_id, owner_pool_id, callback


def _replace_exact(value: Any, replacements: dict[tuple[str, str], Any]) -> Any:
    if isinstance(value, dict):
        if len(value) == 1 and type(next(iter(value.values()))) is str:
            key, child = next(iter(value.items()))
            replacement = replacements.get((key, child))
            if replacement is not None:
                return copy.deepcopy(replacement)
        return {key: _replace_exact(child, replacements) for key, child in value.items()}
    if isinstance(value, list):
        return [_replace_exact(child, replacements) for child in value]
    return value


def build_dev_owner_oauth_template(*, account_id: str, api_id: str,
                                   owner_pool_id: str, callback_url: str) -> dict[str, Any]:
    """Return the fixed three-resource DEV OAuth addition to the owner pool.

    The supplied callback must be the exact intended assisted loopback callback.
    Syntax validation proves neither listener readiness nor Codex registration.
    Client IDs are generated by Cognito and must be privately read back later.
    """
    account_id, api_id, owner_pool_id, callback = _inputs(
        account_id, api_id, owner_pool_id, callback_url,
    )
    resource_uri = f"https://{api_id}.execute-api.{REGION}.amazonaws.com/mcp"
    replacements = {
        ("Ref", "McpResourceUri"): resource_uri,
        ("Fn::Sub", "${McpResourceUri}/use"): f"{resource_uri}/use",
        ("Ref", "OAuthCallbackURL"): callback,
        ("Fn::Sub", "honda-mapit-mcp-${EnvironmentName}"): RESOURCE_SERVER_NAME,
        ("Fn::Sub", "honda-mapit-mcp-${EnvironmentName}-client"): CLIENT_NAME,
    }
    try:
        scaffold = build_shared_identity_oauth_setup_retained_template(
            api_id, owner_pool_id, callback_url=callback,
        )
        source_resources = scaffold.get("Resources")
        if not isinstance(source_resources, dict) or not _RESOURCE_NAMES <= set(source_resources):
            _fail()
        selected: dict[str, dict[str, Any]] = {}
        for logical_id, expected_type in _RESOURCE_TYPES.items():
            source = source_resources.get(logical_id)
            if (not isinstance(source, dict) or source.get("Type") != expected_type
                    or source.get("DeletionPolicy") != "Retain"
                    or source.get("UpdateReplacePolicy") != "Retain"
                    or not isinstance(source.get("Properties"), dict)):
                _fail()
            selected[logical_id] = _replace_exact(source, replacements)

        server = selected["McpResourceServer"]["Properties"]
        client_resource = selected["McpUserPoolClient"]
        client = client_resource["Properties"]
        branding = selected["McpManagedLoginBranding"]["Properties"]
        if (server.get("Identifier") != resource_uri
                or server.get("UserPoolId") != owner_pool_id
                or server.get("Scopes") != [{
                    "ScopeName": "use", "ScopeDescription": "Call the protected MCP endpoint."
                }]
                or client.get("UserPoolId") != owner_pool_id
                or client.get("ClientName") != CLIENT_NAME
                or client.get("AllowedOAuthScopes") != [f"{resource_uri}/use"]
                or client.get("CallbackURLs") != [callback]
                or client.get("DefaultRedirectURI") != callback
                or branding.get("UserPoolId") != owner_pool_id):
            _fail()

        # Never inherit Cognito API sign-in defaults: this client is for
        # authorization-code + PKCE managed login and refresh only.
        client["ExplicitAuthFlows"] = ["ALLOW_REFRESH_TOKEN_AUTH"]
        client["AccessTokenValidity"] = 5
        client["IdTokenValidity"] = 5
        client["RefreshTokenValidity"] = 1
        client["TokenValidityUnits"] = {
            "AccessToken": "minutes", "IdToken": "minutes", "RefreshToken": "days",
        }
        client["AllowedOAuthFlows"] = ["code"]
        client["AllowedOAuthFlowsUserPoolClient"] = True
        client["SupportedIdentityProviders"] = ["COGNITO"]
        client["GenerateSecret"] = False
        client["AllowedOAuthScopes"] = [f"{resource_uri}/use"]
        client_resource["DependsOn"] = ["McpResourceServer"]

        condition = {"Fn::And": [
            {"Fn::Equals": [{"Ref": "AWS::Region"}, REGION]},
            {"Fn::Equals": [{"Ref": "AWS::StackName"}, STACK_NAME]},
            {"Fn::Equals": [{"Ref": "AWS::AccountId"}, account_id]},
        ]}
        for resource in selected.values():
            resource["Condition"] = "SupportedDeployment"
    except DevOwnerOAuthTemplateError:
        raise
    except Exception:
        _fail()

    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "Isolated DEV owner-pool OAuth client candidate; no pool, user, MFA, or runtime changes.",
        "Conditions": {"SupportedDeployment": condition},
        "Metadata": {
            "Readiness": "DEV_OWNER_OAUTH_NOT_DEPLOY_READY",
            "Environment": "dev",
            "Region": REGION,
            "StackName": STACK_NAME,
            "UsesExistingOwnerIdentityPool": True,
            "OwnerAndMfaUnchanged": True,
            "ExistingOauthClientUnchanged": True,
            "PublicClientNoSecret": True,
            "AuthorizationCodePkceOnly": True,
            "RefreshApiFlowOnly": True,
            "NoPoolDomainUserOrRuntimeResources": True,
            "GeneratedClientIdRequiresPrivateReadback": True,
            "NoEndpointActivation": True,
        },
        "Resources": selected,
    }


__all__ = ["build_dev_owner_oauth_template", "DevOwnerOAuthTemplateError"]
